---
abstract: 'A chomp and chop that will return the chomped and chopped'
author:
  - 'Robert Krimen <rkrimen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Chomped
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/robertkrimen/Text-Chomped/tree/master
version: 0.02
